initial commit
This errors on 'str.trimStart()' attempted usage with
target: 'es2017', as we expect.

```
% npm start

> repro-tsc-compilation-target-confusion@1.0.0 start
> tsc --build && node build/src/index.js

src/index.ts:2:27 - error TS2550: Property 'trimStart' does not exist on type '" spaces all around "'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.

2 console.log('s is: %j', s.trimStart());
                            ~~~~~~~~~

Found 1 error.
```